# Generated by Django 5.2.3 on 2025-07-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_ar", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("api_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "platforms",
            },
        ),
        migrations.CreateModel(
            name="DailyPlatformMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("followers", models.PositiveIntegerField()),
                ("engagement", models.PositiveIntegerField(blank=True, null=True)),
                ("reach", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="metrics.platform",
                    ),
                ),
            ],
            options={
                "db_table": "daily_platform_metrics",
                "unique_together": {("platform", "date")},
            },
        ),
    ]
