# Generated by Django 5.2.3 on 2025-07-17 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FetchScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human‑friendly name for the fetch script (e.g. 'Facebook Scraper').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "script_path",
                    models.CharField(
                        help_text="Dotted path to your fetcher class, e.g. 'fetchers.facebook.FacebookFetcher'",
                        max_length=255,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this script was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this script was last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fetch Script",
                "verbose_name_plural": "Fetch Scripts",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="dailyplatformmetric",
            options={
                "ordering": ("-date",),
                "verbose_name": "Daily Platform Metric",
                "verbose_name_plural": "Daily Platform Metrics",
            },
        ),
        migrations.AlterModelOptions(
            name="platform",
            options={
                "ordering": ("name",),
                "verbose_name": "Platform",
                "verbose_name_plural": "Platforms",
            },
        ),
        migrations.RemoveField(
            model_name="dailyplatformmetric",
            name="engagement",
        ),
        migrations.RemoveField(
            model_name="dailyplatformmetric",
            name="reach",
        ),
        migrations.RemoveField(
            model_name="platform",
            name="api_url",
        ),
        migrations.AddField(
            model_name="platform",
            name="page_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the platform page (e.g. https://facebook.com/YourPage).",
                max_length=300,
                verbose_name="Page URL",
            ),
        ),
        migrations.AlterField(
            model_name="dailyplatformmetric",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this metric entry was created.",
            ),
        ),
        migrations.AlterField(
            model_name="dailyplatformmetric",
            name="date",
            field=models.DateField(
                help_text="Date for which the metrics are recorded."
            ),
        ),
        migrations.AlterField(
            model_name="dailyplatformmetric",
            name="followers",
            field=models.PositiveIntegerField(
                help_text="Number of followers on this date."
            ),
        ),
        migrations.AlterField(
            model_name="dailyplatformmetric",
            name="platform",
            field=models.ForeignKey(
                help_text="The platform this metric entry belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="metrics.platform",
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="color",
            field=models.CharField(
                help_text="Hex color code for the platform (e.g. '#4267B2').",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this platform was created."
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the platform. Auto-generated.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if this platform is currently active and tracked.",
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="name",
            field=models.CharField(
                help_text="Platform name in English (e.g. 'Facebook').", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="name_ar",
            field=models.CharField(
                help_text="Platform name in Arabic.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this platform was last updated.",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyplatformmetric",
            index=models.Index(fields=["date"], name="daily_platf_date_95df3d_idx"),
        ),
        migrations.AddField(
            model_name="platform",
            name="fetch_script",
            field=models.OneToOneField(
                blank=True,
                help_text="Script to run for pulling this platform’s metrics.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="platform",
                to="metrics.fetchscript",
            ),
        ),
        migrations.AddIndex(
            model_name="platform",
            index=models.Index(fields=["name"], name="platforms_name_3ccd75_idx"),
        ),
    ]
