version: '3.8'

services:
  rawad_database:
    image: postgres:17-alpine
    container_name: rawad_database
    environment:
      POSTGRES_DB: rawad_db
      POSTGRES_USER: rawad_user
      POSTGRES_PASSWORD: rawad_password_2025
    volumes:
      - rawad_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rawad_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rawad_user -d rawad_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  rawad_redis:
    image: redis:8.0-alpine
    container_name: rawad_redis
    command: redis-server --requirepass rawad_redis_password_2025
    volumes:
      - rawad_redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - rawad_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  rawad_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rawad_backend
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      rawad_database:
        condition: service_healthy
      rawad_redis:
        condition: service_healthy
    networks:
      - rawad_network
    restart: unless-stopped
    expose:
      - "8000"

  rawad_celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rawad_celery_worker
    command: celery -A core worker --loglevel=info --concurrency=4
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
    volumes:
      - ./media:/app/media
    depends_on:
      rawad_database:
        condition: service_healthy
      rawad_redis:
        condition: service_healthy
    networks:
      - rawad_network
    restart: unless-stopped

  rawad_nginx:
    image: nginx:1.27-alpine
    container_name: rawad_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
      - ./config/ssl:/etc/nginx/ssl:ro
    depends_on:
      - rawad_backend
    networks:
      - rawad_network
    restart: unless-stopped

volumes:
  rawad_postgres_data:
    driver: local
  rawad_redis_data:
    driver: local

networks:
  rawad_network:
    driver: bridge
